[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'scrooloose/syntastic.git'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tell-k/vim-autopep8'

[[plugins]]
repo = 'deris/vim-duzzle'
